apiVersion: v1
kind: Service
metadata:
  name: {{ include "web" . }}
spec:
  selector:
    app: {{ include "app" . }}
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app" . }}
  template:
    metadata:
      labels:
        app: {{ include "app" . }}
    spec:
      containers:
        - name: {{ include "web" . }}
          image: nginx:1.7.9
          ports:
            - containerPort: 80
